### ISSUE TITLE
cherrypy database: where did these new fields come from?

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#614]
We got the cherrypy server running again at AWS and now when I try to submit results I see this HTTP error in the response back from the server
```Internal Server Error
<<<<<<<---------------- Raw Output (Start) ---------------->>>>>>
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/dispatchers.py", line 360, in POST
    value = self._db.insert_test_run(submit_info['submit_id'], data['metadata'], entry)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 1781, in insert_test_run
    fields, values)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 595, in _select_insert
    cursor.execute( select_stmt, values )
ProgrammingError: column "clck_id" does not exist
LINE 3: ... environment_id = 0 AND result_message_id = 1 AND clck_id = ...
                                                             ^

</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.0</a>
      </span>
    </div>
    </body>
</html>
```

anyone know what this clck_id thing is?

**Comment by noahv** [comment]
Checking on it now.  -- Noah

**Comment by ribab** [comment]
Hi Howard,

The issue is that you are using an older Database Schema.

Try and test this patch and see if it makes your code more backwards compatible, you'll have to restart the cherrypy server after applying the change:

```diff
diff --git a/server/php/cherrypy/src/webapp/db_pgv3.py b/server/php/cherrypy/src/webapp/db_pgv3.py
index 95cfb9c..16cd433 100644
--- a/server/php/cherrypy/src/webapp/db_pgv3.py
+++ b/server/php/cherrypy/src/webapp/db_pgv3.py
@@ -559,6 +559,9 @@ class DatabaseV3():
     def _select_insert(self, table, table_id, stmt_fields, stmt_values):
         found_id = -1

+        cursor.execute("SELECT * FROM %s LIMIT 0" % table)
+        all_fields_for_table = [d[0] for d in curs.description]
+
         #
         # Build the SELECT and INSERT statements
         #
@@ -567,6 +570,9 @@ class DatabaseV3():

         count = 0
         for field in stmt_fields:
+            if field not in all_fields_for_table:
+                self._logger.debug("WARNING: _select_insert field %s not in table %s" % (field, table))
+                continue
             insert_stmt = insert_stmt + ", " + field

             if count == 0:
```

Thanks --Ricky

**Comment by hppritcha** [comment]
@jjhursey  could you patch the server?

**Comment by jjhursey** [comment]
@hppritcha I applied the patch to the CherryPy server. Please give it another try.

**Comment by jjhursey** [comment]
A couple modifications so far:
```
+        cursor = self.get_cursor()
+        cursor.execute("SELECT * FROM %s LIMIT 0" % table)
+        all_fields_for_table = [d[0] for d in cursor.description]
```

Now we get the following error message:
```
Traceback (most recent call last):
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/env/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/dispatchers.py", line 360, in POST
    value = self._db.insert_test_run(submit_info['submit_id'], data['metadata'], entry)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 1788, in insert_test_run
    fields, values)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 602, in _select_insert
    cursor.execute( select_stmt, values )
TypeError: not all arguments converted during string formatting
```

**Comment by hppritcha** [comment]
okay I think I see what's wrong here.  That patch isn't sufficient.  We also need to prune the ```stmt_values``` otherwise it borks up the cursor.execute thing.
