### ISSUE TITLE
IPMITool plugin type error

### ISSUE THREAD

**Issue by beardeddog** [open-mpi/mtt#867]
running the IPMITool plugin with python3, got this error

```
Executing plugin IPMITool
IPMITool execute
IPMITool: target controller username password pwfile command maxtries numthreads dryrun sudo modules_unload modules modules_swap trial scratchdir description platform organization merge_stdout_stderr stdout_save_lines stderr_save_lines executor time
=======================================
Exception was raised: <class 'TypeError'> '<' not supported between instances of 'int' and 'tuple'
=======================================
Traceback (most recent call last):

  File "/opt/mtt/pylib/Tools/Executor/sequential.py", line 290, in execute_sections
    plugin.execute(stageLog, keyvals, testDef)

  File "/opt/mtt/pylib/Tools/CNC/IPMITool.py", line 303, in execute
    if len(targets) < self.options['numthreads']:

TypeError: '<' not supported between instances of 'int' and 'tuple'
```

**Comment by beardeddog** [comment]
this  has been fixed
