### ISSUE TITLE
CherryPy server internal error when submitting results from Python client

### ISSUE THREAD

**Issue by sunkuamzn** [open-mpi/mtt#940]
Relevant config
```
[MTTDefaults]
scratchdir = scratch
description = OMPIv4.1.x
platform = aws-amazonlinux-slurm
executor = sequential
organization = amazon

[Profile:Installed]

[ASIS MiddlewareGet:OMPI]
plugin = OMPI_Snapshot
url = https://download.open-mpi.org/nightly/open-mpi/v4.1.x
mpi_name = ompi-nightly-main

[MiddlewareBuild:OMPI]
parent = MiddlewareGet:OMPI
plugin = Autotools
configure_options = --enable-debug --enable-mpi1-compatibility --enable-slurm=no --enable-munge=no
make_options = -j 32

<snip>

[Reporter: MTTDatabase]
plugin = IUDatabase
realm = OMPI
username = amazon
password = <removed>
platform = aws-amazonlinux-slurm
url = https://mtt.open-mpi.org/submit/cpy/api
debug_filename = "/tmp/mtt-reporter-debug"
keep_debug_files = True
debug_server = True
debug_screen = True
```

Get a 500 from CherryPy

```
----------------- MPI Install (MiddlewareBuild:OMPI) 
{   'compiler': {   'compiler': 'gnu',
                    'status': 0,
                    'version': 'gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)'},
    'configure': ([], []),
    'elapsed': 254.121754,
    'endtime': datetime.datetime(2022, 12, 9, 13, 25, 50, 596375),
    'location': '/home/ec2-user/PortaFiducia/workloads/mtt/job/wtjw9k/scratch/MiddlewareBuild_OMPI',
    'make_all': ([], []),
    'make_clean': ([], []),
    'options': {   'autogen_cmd': None,
                   'build_in_place': False,
                   'checkpoint_file': None,
                   'configure_options': '--enable-debug '
                                        '--enable-mpi1-compatibility '
                                        '--enable-slurm=no --enable-munge=no',
                   'dependencies': None,
                   'description': 'OMPIv4.1.x',
                   'executor': 'sequential',
                   'make_envars': None,
                   'make_options': '-j 32',
                   'merge_stdout_stderr': False,
                   'middleware': None,
                   'modules': None,
                   'modules_swap': None,
                   'modules_unload': None,
                   'organization': 'amazon',
                   'parent': 'MiddlewareGet:OMPI',
                   'platform': 'aws-amazonlinux-slurm',
                   'restart_file': None,
                   'scratchdir': '/home/ec2-user/PortaFiducia/workloads/mtt/job/wtjw9k/scratch',
                   'stderr_save_lines': -1,
                   'stdout_save_lines': -1,
                   'subdir': None,
                   'time': False,
                   'trial': False},
    'parameters': [   ('parent', 'MiddlewareGet:OMPI'),
                      ('plugin', 'Autotools'),
                      (   'configure_options',
                          '--enable-debug --enable-mpi1-compatibility '
                          '--enable-slurm=no --enable-munge=no'),
                      ('make_options', '-j 32')],
    'parent': 'MiddlewareGet:OMPI',
    'result': 1,
    'section': 'MiddlewareBuild:OMPI',
    'starttime': datetime.datetime(2022, 12, 9, 13, 21, 36, 474621),
    'status': 0,
    'stderr': [   "libtool: warning: relinking 'mca_allocator_basic.la'",

<snip>
                  "libtool: warning: relinking 'mca_vprotocol_pessimist.la'"],
    'stdout': [   'Making install in config',
                  'make[1]: Entering directory '

<snip>

                  'make[1]: Leaving directory '
                  "`/home/ec2-user/PortaFiducia/workloads/mtt/job/wtjw9k/scratch/MiddlewareGet_OMPI/openmpi-v4.1.x-202212060349-5980bac'"]}
<<<<<<<---------------- Payload (Start) -------------------------->>>>>>
{
    "data": [
        {
            "compiler_name": "gnu",
            "compiler_version": "gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)",
            "configure_arguments": null,
            "description": "OMPIv4.1.x",
            "environment": "",
            "exit_value": 0,
            "merge_stdout_stderr": 0,
            "mpi_name": "ompi-nightly-main",
            "mpi_version": "v4.1.x-202212060349-5980bac",
            "os_name": "Linux",
            "os_version": "4.14.262-200.489.amzn2.x86_64",
            "platform_hardware": "x86_64",
            "platform_type": "x86_64",
            "result_message": "Success",
            "result_stderr": "libtool: warning: relinking 'mca_allocator_basic.la'\n

<snip>

libtool: warning: relinking 'mca_vprotocol_pessimist.la'",
"result_stdout": "Making install in config\nmake[1]: Entering directory 

<snip>

make[1]: Leaving directory `/home/ec2-user/PortaFiducia/workloads/mtt/job/wtjw9k/scratch/MiddlewareGet_OMPI/openmpi-v4.1.x-202212060349-5980bac'",
            "start_timestamp": "Fri Dec  9 13:45:35 2022",
            "test_result": 1
        }
    ],
    "metadata": {
        "client_serial": 4123372,
        "hostname": "ip-172-31-36-230",
        "http_username": "amazon",
        "local_username": "ec2-user",
        "mtt_client_version": "4.0a1",
        "phase": "MPI Install",
        "platform_name": "aws-amazonlinux-slurm",
        "trial": 0
    }
}
<<<<<<<---------------- Payload (End  ) -------------------------->>>>>>
<<<<<<<---------------- Response -------------------------->>>>>>
Result: 500: text/html;charset=utf-8
{'Date': 'Fri, 09 Dec 2022 13:45:36 GMT', 'Server': 'CherryPy/8.9.1', 'Content-Type': 'text/html;charset=utf-8', 'Allow': 'GET, HEAD, POST', 'Access-Control-Allow-Origin': '*', 'Content-Length': '2055', 'Set-Cookie': 'session_id=d64c8553aeffa351f41b08de116a1bf069dfc15f; expires=Fri, 09 Dec 2022 14:45:36 GMT; Path=/', 'Connection': 'close'}
Internal Server Error
```

**Comment by sunkuamzn** [comment]
Not an authentication issue because some trivial input succeeded

```
Executing plugin IUDatabase
<<<<<<<---------------- Payload (Start) -------------------------->>>>>>
{
    "serial": "serial"
}
<<<<<<<---------------- Payload (End  ) -------------------------->>>>>>
<<<<<<<---------------- Response -------------------------->>>>>>
Result: 200: application/json
{'Date': 'Fri, 09 Dec 2022 13:45:32 GMT', 'Server': 'CherryPy/8.9.1', 'Content-Type': 'application/json', 'Allow': 'GET, HEAD, POST', 'Access-Control-Allow-Origin': '*', 'Content-Length': '68', 'Set-Cookie': 'session_id=ba4670555e390f15b73f8c301b3da2d33916f5e1; expires=Fri, 09 Dec 2022 14:45:32 GMT; Path=/', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive'}
OK
<<<<<<<---------------- Raw Output (Start) ---------------->>>>>>
{"status": 0, "status_message": "Success", "client_serial": 4123372}
<<<<<<<---------------- Raw Output (End  ) ---------------->>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by sunkuamzn** [comment]
I can debug this more but I would need access to the server logs. I set `debug_server = True` in the reporter config but I don't see any logs from the server

**Comment by sunkuamzn** [comment]
Found a bit more info in the raw output from the server

```
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/dispatchers.py", line 337, in POST
    submit_info = self._db.get_submit_id(data['metadata'])
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 674, in get_submit_id
    submit_id = self._select_insert("submit", "submit_id", fields, values)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 573, in _select_insert
    cursor.execute("SELECT * FROM %s LIMIT 0" % table)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by rhc54** [comment]
There was a time, at least, when the only one with access to the server was @jjhursey - I don't know if that is still true?

**Comment by hppritcha** [comment]
i'm taking a look at the log.  today is my day off so may not be able to fix this till Monday.

**Comment by hppritcha** [comment]
probably related to another incidence of

https://github.com/open-mpi/mtt/pull/931

**Comment by hppritcha** [comment]
could you post the entire ini file (except for passwords/user names)?

**Comment by sunkuamzn** [comment]
Sure https://gist.github.com/sunkuamzn/856dd1777d2af7ebbe45c71724e2e38c

But irrespective of what happens in the test sections, the reporting of the OMPI install should work

**Comment by hppritcha** [comment]
could you rerun your problem MTT now and i'll watch the log?

**Comment by sunkuamzn** [comment]
Do you want me to remove the TestRun sections? Because those take a long time to run and the reporter isn't triggered until all those sections finish, so you won't see anything for several hours.

**Comment by hppritcha** [comment]
yes remove the testrun section

**Comment by hppritcha** [comment]
Hmm... looks like something strange happened I've not seen before:
```
[08/Dec/2022:19:19:03] HTTP
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs) 
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/dispatchers.py", line 352, in POST
    value = self._db.insert_mpi_install(submit_info['submit_id'], data['metadata'], entry)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 1081, in insert_mpi_install
    mpi_install_id = self._select_insert("mpi_install",
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 621, in _select_insert
    cursor.execute( select_stmt, values )
psycopg2.errors.UndefinedFunction: operator does not exist: text = text[]
LINE 3: ...D merge_stdout_stderr = 'false' AND result_stderr = ARRAY['P...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

  
[08/Dec/2022:19:19:04] HTTP
Request Headers:
  Remote-Addr: 127.0.0.1 
  HOST: 127.0.0.1:9080
  USER-AGENT: python-requests/2.28.1
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  COOKIE: session_id=66e9e99aab3e7e5b8f2f172003fbb96b4235419e
  AUTHORIZATION: Basic YW1hem9uOjZXWjhUVDdX
  X-FORWARDED-FOR: 52.88.34.183
  X-FORWARDED-HOST: mtt.open-mpi.org
  X-FORWARDED-SERVER: mtt.open-mpi.org
  CONNECTION: close
  Content-Type: application/json
  Content-Length: 844
[08/Dec/2022:19:19:04] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/dispatchers.py", line 337, in POST
    submit_info = self._db.get_submit_id(data['metadata'])
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 674, in get_submit_id
    submit_id = self._select_insert("submit", "submit_id", fields, values)
  File "/mnt/data/mtt.open-mpi.org/mtt/server/php/cherrypy/src/webapp/db_pgv3.py", line 573, in _select_insert
    cursor.execute("SELECT * FROM %s LIMIT 0" % table)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

```

**Comment by hppritcha** [comment]
okay so it was your submissions that caused the cherrypy server grief. looking to see what could be different about your ini file that would cause this.

**Comment by sunkuamzn** [comment]
Restarting the CheryPy server seemed to have fixed the issue
